services:
  database:
    image: postgres:11.12-alpine
    container_name: database_pg
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: backend-challenge

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - database
    environment:
      PORT: 3333
      DATABASE_PORT: 5432
      NODE_ENV: development
      DATABASE_HOST: database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 12345678
      DATABASE_NAME: backend-challenge
      ACCESS_TOKEN_VALIDITY_DURATION_IN_DAYS: 1d
      JWT_SECRET: 3e3d225259318ab0c41f51324ca3a71e8a88cdf1390

volumes:
  database:
