services:
  database:
    image: postgres:11.12-alpine
    container_name: database_pg
    restart: always
    env_file:
      - .env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - database
    env_file:
      - .env

volumes:
  database:
